#!/usr/bin/env python
# encoding: utf-8

import sys
sys.path.insert(0, sys.path[0]+'/waf_tools')

VERSION = '1.0.0'
APPNAME = 'omni_dart'

srcdir = 'src'
blddir = 'build'


def options(opt):
    opt.add_option('--resibots', type='string', help='path to resibots', dest='resibots')
    opt.load('compiler_cxx')
    opt.load('boost')
    opt.load('eigen')
    opt.load('dart')


def configure(conf):
    conf.load('compiler_cxx')
    conf.load('boost')
    conf.load('eigen')
    conf.load('dart')

    conf.check_boost(lib='system filesystem', min_version='1.39', required=True)
    conf.check_eigen(required=True)
    conf.check_dart(required=True, require_graphics=False)

    if conf.env.CXX_NAME in ["icc", "icpc"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -xHost  -march=native -mtune=native -unroll -fma -g"
    elif conf.env.CXX_NAME in ["clang"]:
        common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"
    else:
        if int(conf.env.CC_VERSION[0] + conf.env.CC_VERSION[1]) < 47:
            common_flags = "-Wall -std=c++0x"
        else:
            common_flags = "-Wall -std=c++11"
        opt_flags = " -O3 -march=native -g"

    all_flags = common_flags + opt_flags
    conf.env['CXXFLAGS'] = conf.env['CXXFLAGS'] + all_flags.split(' ')


def build(bld):
    bld.program(features='cxxprogram',
                source='src/test.cpp',
                includes='include',
                uselib='BOOST EIGEN DART DART_GRAPHIC',
                target='omni_dart_test')

    bld.install_files('${PREFIX}', bld.path.ant_glob('include/omni_dart/*.hpp'), relative_trick=True)
